#!/bin/bash

if [[ $# -ne 2 ]]; then
    echo "Usage: $0 <input_file> <output_file>" >&2
    echo "Example: $0 access.log access.bots.log" >&2
    exit 1
fi

LOG_FILE="$1"
OUTPUT_FILE="$2"

# Taken from: https://udger.com/resources/ua-list/crawlers
BOTS=(
    "uptime\.bot"
    "Online Domain Tools"
    "BetterStack"
    "monitorbacklinks\.com"
    "Uptimia"
    "WebGazer"
    "GotSiteMonitor"
    "ByteDance"
    "Blogtrottr"
    "AhrefsBot"
    "Googlebot"
    "monitoring360bot"
    "Irokez"
    "SEMrushBot"
    "FreeWebMonitoring"
    "NIXStatsbot"
    "OAI-SearchBot"
    "GPTBot"
    "ChatGPT-User"
    "UptimeRobot"
    "updown\.io"
    "Twitterbot"
    "Monibot"
    "anthropic-ai"
    "ClaudeBot"
    "MonTools"
    "Site24x7"
    "Google-Read-Aloud"
    "facebookexternalhit"
    "FacebookBot"
    "PerplexityBot"
    "Scrapy"
    "YandexBot"
    "SeznamBot"
    "Specificfeeds"
    "SlaccaleBot"
    "coccocbot"
    "ALittle Client"
    "RankurBot"
    "Algolia"
    "OpenWebSearch"
    "WPMU DEV"
    "Baiduspider"
    "PetalBot"
    "Expanse"
    "Prometheus"
    "libredtail"
    "xfa1"
    "MJ12bot"
    "Chrome-Lighthouse"
    "YisouSpider"
    "downnotifier"
    "HeadlessChrome"
    "SecurityHeaders"
    "pulsetic"
    "Applebot"
    "StatusNest"
    "Barkrowler"
    "sogou"
    "Mediapartners-Google"
    "AdsBot-Google"
    "HetrixTools"
    "Chrome Privacy Preserving Prefetch"
    "CloudFlare"
    "Amazonbot"
    "DotBot"
    "FeedBurner"
    "bingbot"
    "TikTok"
    "Cronless"
    "WordPress\.com"
    "MojeekBot"
    "TurnitinBot"
    "Lenns\.io"
    "DuckAssistBot"
    "mediaboardbot"
    "Feedspotbot"
    "wpbot"
    "FirmoGraph"
    "Dataprovider"
    "IbouBot"
    "NaverBot"
    "linkfluence"
    "Qwantbot"
    "BuiltWith"
    "Brightbot"
    "OnlineOrNot"
    "yacybot"
    "WhatWeb"
    "WPSec"
    "WPScan"
    "Pagespeed"
    "Awario"
    "WebCrawler"
    "TestBot"
    "RSSingBot"
    "SkypeUriPreview"
    "Hatena"
    "DuckDuckBot"
    "fluid"
    "Google-InspectionTool"
    "Storebot-Google"
    "Google-Safety"
    "FlipboardBot"
    "HanaleiBot"
    "HaloScan"
    "DataForSeo"
    "SpiderLing"
    "LivelapBot"
    "censys"
    "QuillBot"
    "Slackbot"
    "hyScore"
    "Orbbot"
    "Observer"
    "2ip\.ru"
    "CSIRT"
    "masscan"
    "Google-Adwords"
    "BitSight"
    "SmartBotCrawler"
    "Cypex"
    "BLEXBot"
    "WF search"
    "MistralAI"
    "Bravebot"
    "WRTNBot"
    "Zoom"
    "UASlinkChecker"
    "bnf\.fr"
    "MetadataScraper"
    "SISTRIX"
    "Google-NotebookLM"
    "SEBot"
    "AsyncHttpClient"
    "archive\.org_bot"
    "Neevabot"
    "CriteoBot"
    "SemrushBot"
    "ImagesiftBot"
    "Discordbot"
    "LinkedInBot"
    "WhatsApp"
    "TelegramBot"
    "PinterestBot"
    "Embedly"
    "Quora-Bot"
    "redditbot"
    "Snapchat"
    "vkShare"
    "W3C_Validator"
    "Validator\.nu"
    "FeedValidator"
    "CCBot"
    "ia_archiver"
    "curl"
    "wget"
    "python-requests"
    "Go-http-client"
    "Java"
    "libwww-perl"
    "Apache-HttpClient"
    "okhttp"
    "axios"
    "node-fetch"
    "PostmanRuntime"
    "insomnia"
    "httpx"
    "aiohttp"
    "Nutch"
    "Heritrix"
    "Screaming Frog"
    "rogerbot"
    "Exabot"
    "ZoominfoBot"
    "SurveyBot"
    "spbot"
    "linkdexbot"
    "lipperhey"
    "AddSearchBot"
    "GroupHigh"
    "theoldreader"
    "Feedly"
    "NewsBlur"
    "Inoreader"
    "BazQux"
    "TheOldReader"
    "SimplePie"
    "NetNewsWire"
    "Tiny Tiny RSS"
    "FreshRSS"
)

PATTERN=$(IFS="|"; echo "${BOTS[*]}")

if command -v rg &>/dev/null; then
    rg -i "$PATTERN" "$LOG_FILE" > "$OUTPUT_FILE"
else
    grep -Ei "$PATTERN" "$LOG_FILE" > "$OUTPUT_FILE"
fi

COUNT=$(wc -l < "$OUTPUT_FILE")
echo "Filtered $COUNT bot requests to $OUTPUT_FILE"
